### ISSUE TITLE
Memory hotplug: Respect auto_online_blocks value

### ISSUE THREAD

**Issue by robert-hoo** [redhat-plumbers/systemd-rhel8#173]
**systemd version**
> 239

**Used distribution**
 > CentOS 8.1

**Expected behaviour you didn't see**
 > Respect /sys/device/system/memory/auto_online_blocks settings

**Unexpected behaviour you saw**
 > Despite  /sys/device/system/memory/auto_online_blocks = offline, /lib/udev/rules.d/40-redhat.rules always unconditionally online hotplugged memory blocks.

**Steps to reproduce the problem**

1. Create VM
2. In qemu monitor, hotplug memory
3. You'll see though by default  /sys/device/system/memory/auto_online_blocks = offline, those new memory blocks are onlined by udev.

**Comment by robert-hoo** [comment]
#174

**Comment by jamacku** [comment]
If it still occurs, please report this issue using our [tracking system](https://github.com/redhat-plumbers/systemd-rhel8/blob/main/CONTRIBUTING.md#filing-issues). We don't support GitHub Issues.
