### ISSUE TITLE
239-58 session leak issues:  User manager's SuccessAction=exit-force  isn't subject to any timeout, is it?

### ISSUE THREAD

**Issue by gleventhal** [redhat-plumbers/systemd-rhel8#289]
**systemd version the issue has been seen with**
> ...systemd-239-58.el8.x86_64

**Used distribution**
 > …Rocky Linux release 8.6 (Green Obsidian)

**Expected behaviour you didn't see**
 > …(systemd-logind) Sessions to close when user disconnects

**Unexpected behaviour you saw**
 > …Sessions leaking until D-bus was saturated and slow, the load spiked 100X what it should be, hitting the configured sessionmax

**Steps to reproduce the problem** run this version of systemd with lots of uses running short-lived ssh sessions, many that perform a bunch of automount activity

Before the switch to SuccessAction=exit-force in /usr/lib/systemd/user/systemd-exit.service, user sessions were ended with systemctl --force exit as an ExecStart command.  Now it uses SuccessAction, which waits for either failed or not active state to occur, but my sessions that are leaked appear to be in the opening or closing state (for days).

Is there no timer that can be used here to prevent the session leak?

**Comment by jamacku** [comment]
If it still occurs, please report this issue using our [tracking system](https://github.com/redhat-plumbers/systemd-rhel8/blob/main/CONTRIBUTING.md#filing-issues). We don't support GitHub Issues.
